# --------- cluster_orders -----------

insert into oasis_new.cluster_orders (id,
                                  created_at,
                                  updated_at,
                                  order_id,
                                  cluster_id,
                                  instance_group_id,
                                  instance_id,
                                  data)
select @new_id := UUID() id,
       old.created_at,
       old.updated_at,
       old.order_id,
       old.cluster_id,
       old.instance_group_id,
       old.instance_id,
       old.data
from (select created_at,
    updated_at,
    order_id,
    cluster_id,
    instance_group_id,
    instance_id,
    data
    from oasis.cluster_orders
    ) old;

# --------- clusters -----------

insert into oasis_new.clusters (id,
                            created_at,
                            updated_at,
                            name,
                            description,
                            cluster_type,
                            distribution_version,
                            main_version,
                            region,
                            availability_zone,
                            image_id,
                            anti_affinity,
                            management_private_key,
                            management_public_key,
                            management_keypair_id,
                            security_group_id,
                            status,
                            status_description,
                            extra,
                            rollback_info,
                            is_terminate_protection,
                            install_apps,
                            enable_eip,
                            eip_line_id,
                            eip_bandwidth,
                            slb_id,
                            activated_at,
                            terminated_at,
                            ks3_credential,
                            vpc_domain_id,
                            vpc_subnet_id,
                            vpc_endpoint_id,
                            charge_type,
                            expire_time,
                            purchase_time,
                            tenant_id,
                            ksc_user_id,
                            ksc_sub_user_id,
                            order_id)
select old.id,
       old.created_at,
       old.updated_at,
       old.name,
       old.description,
       old.cluster_type,
       old.distribution_version,
       old.main_version,
       old.region,
       old.availability_zone,
       old.image_id,
       old.anti_affinity,
       old.management_private_key,
       old.management_public_key,
       old.management_keypair_id,
       old.security_group_id,
       old.status,
       old.status_description,
       old.extra,
       old.rollback_info,
       old.is_terminate_protection,
       old.install_apps,
       old.enable_eip,
       old.eip_line_id,
       old.eip_bandwidth,
       old.slb_id,
       old.activated_at,
       old.terminated_at,
       old.ks3_credential,
       old.vpc_domain_id,
       old.vpc_subnet_id,
       old.vpc_endpoint_id,
       old.charge_type,
       old.expire_time,
       old.purchase_time,
       old.tenant_id,
       old.ksc_user_id,
       old.ksc_sub_user_id,
       old.order_id
from (select id,
             created_at,
             updated_at,
             name,
             description,
             cluster_type,
             distribution_version,
             main_version,
             region,
             availability_zone,
             image_id,
             anti_affinity,
             management_private_key,
             management_public_key,
             management_keypair_id,
             security_group_id,
             status,
             status_description,
             extra,
             rollback_info,
             is_terminate_protection,
             install_apps,
             enable_eip,
             eip_line_id,
             eip_bandwidth,
             slb_id,
             activated_at,
             terminated_at,
             ks3_credential,
             vpc_domain_id,
             vpc_subnet_id,
             vpc_endpoint_id,
             charge_type,
             expire_time,
             purchase_time,
             tenant_id,
             ksc_user_id,
             ksc_sub_user_id,
             order_id
      from oasis.clusters
     ) old;

# --------- eip_infos -----------

insert into oasis_new.eip_infos (id,
                             created_at,
                             updated_at,
                             cluster_id,
                             load_balancer_id,
                             listener_id,
                             health_check_id,
                             allocate_address_id,
                             eip_address,
                             eip_line_id,
                             eip_charge_type,
                             eip_order_id,
                             status)
select @new_id := UUID() id,
       old.created_at,
       old.updated_at,
       old.cluster_id,
       old.load_balancer_id,
       old.listener_id,
       old.health_check_id,
       old.allocate_address_id,
       old.eip_address,
       old.eip_line_id,
       old.eip_charge_type,
       old.eip_order_id,
       old.status
from (select created_at,
    updated_at,
    cluster_id,
    load_balancer_id,
    listener_id,
    health_check_id,
    allocate_address_id,
    eip_address,
    eip_line_id,
    eip_charge_type,
    eip_order_id,
    status
    from oasis.eip_infos
    ) old;

# --------- instance_groups -----------

insert into oasis_new.instance_groups (id,
                                   created_at,
                                   updated_at,
                                   name,
                                   resource_type,
                                   instance_type_code,
                                   instance_group_type,
                                   image_id,
                                   resource_attr,
                                   count,
                                   dest_count,
                                   cluster_id,
                                   availability_zone,
                                   vpc_domain_id,
                                   vpc_subnet_id,
                                   system_volume_type,
                                   system_volume_size,
                                   volume_type,
                                   volume_count,
                                   volume_size,
                                   order_id,
                                   status)
select old.id,
       old.created_at,
       old.updated_at,
       old.name,
       old.resource_type,
       old.instance_type_code,
       old.instance_group_type,
       old.image_id,
       old.resource_attr,
       old.count,
       old.dest_count,
       old.cluster_id,
       old.availability_zone,
       cl.vpc_domain_id,
       cl.vpc_subnet_id,
       old.system_volume_type,
       old.system_volume_size,
       old.volume_type,
       old.volume_count,
       old.volume_size,
       old.order_id,
       'Active'
from (select id,
             created_at,
             updated_at,
             name,
             resource_type,
             instance_type_code,
             instance_group_type,
             image_id,
             resource_attr,
             count,
             dest_count,
             cluster_id,
             availability_zone,
             vpc_domain_id,
             vpc_subnet_id,
             system_volume_type,
             system_volume_size,
             volume_type,
             volume_count,
             volume_size,
             order_id,
             status
      from oasis.instance_groups
     ) old
         left join oasis.clusters cl
                   on cl.id = old.cluster_id;

# --------- instances -----------

insert into oasis_new.instances (id,
                             created_at,
                             updated_at,
                             instance_id,
                             instance_name,
                             instance_group_id,
                             internal_ip,
                             management_ip,
                             management_ip_line,
                             management_ip_type,
                             inner_eip,
                             volumes,
                             cpus,
                             ram,
                             host_name,
                             data_guard_id,
                             slb_register_id,
                             service_instance_id,
                             status,
                             inner_manager_ip,
                             allocate_address_id)
select old.id,
       old.created_at,
       old.updated_at,
       old.instance_id,
       old.instance_name,
       old.instance_group_id,
       old.internal_ip,
       old.management_ip,
       old.management_ip_line,
       old.management_ip_type,
       old.inner_eip,
       old.volumes,
       old.cpus,
       old.ram,
       old.host_name,
       old.data_guard_id,
       old.slb_register_id,
       old.service_instance_id,
       old.status,
       old.inner_manager_ip,
       old.allocate_address_id
from (select id,
             created_at,
             updated_at,
             instance_id,
             instance_name,
             instance_group_id,
             internal_ip,
             management_ip,
             management_ip_line,
             management_ip_type,
             inner_eip,
             volumes,
             cpus,
             ram,
             host_name,
             data_guard_id,
             slb_register_id,
             service_instance_id,
             status,
             inner_manager_ip,
             allocate_address_id
      from oasis.instances
     ) old;

# --------- users -----------

insert into oasis_new.users (id,
                         created_at,
                         updated_at,
                         tenant_id,
                         total_virtual_cpu,
                         total_mem_mb,
                         total_disk_gb,
                         allocated_virtual_cpu,
                         allocated_mem_mb,
                         allocated_disk_gb,
                         lifespan,
                         role,
                         allocator,
                         description,
                         extra,
                         expire_time)
select old.user_id,
       old.created_at,
       old.updated_at,
       old.tenant_id,
       old.total_virtual_cpu,
       old.total_mem_mb,
       old.total_disk_gb,
       old.allocated_virtual_cpu,
       old.allocated_mem_mb,
       old.allocated_disk_gb,
       old.lifespan,
       old.role,
       old.allocator,
       old.description,
       old.extra,
       old.expire_time
from (select created_at,
             updated_at,
             user_id,
             tenant_id,
             total_virtual_cpu,
             total_mem_mb,
             total_disk_gb,
             allocated_virtual_cpu,
             allocated_mem_mb,
             allocated_disk_gb,
             lifespan,
             role,
             allocator,
             description,
             extra,
             expire_time
      from oasis.users) old;


insert ignore into oasis_new.gg_components select * from oasis.gg_components;

insert ignore into oasis_new.gg_node_config select * from oasis.gg_node_config;

insert ignore into oasis_new.gg_node_config_his select * from oasis.gg_node_config_his;

insert ignore into oasis_new.gg_node_group_config select * from oasis.gg_node_group_config;

insert ignore into oasis_new.gg_node_group_config_his select * from oasis.gg_node_group_config_his;

insert ignore into oasis_new.flavors select * from oasis.flavors;

insert ignore into oasis_new.gg_cluster_infos select * from oasis.gg_cluster_infos;

insert ignore into oasis_new.gg_operation select * from oasis.gg_operation;

insert ignore into oasis_new.gg_task_audit select * from oasis.gg_task_audit;

